### ISSUE TITLE
forge ronde eindigt te vroeg

### ISSUE THREAD

**Issue by jonascrevecoeur** [thomashertog/dice-forge-ai#26]
Met 12 goud op het begin van mijn beurt wou ik aankopen:
- 2 rood voor 8 goud
- 1 blauw voor 2 goud
- 3 goud zijde voor 2 goud

Echter na aankoop van de eerste 2 zijdes ging de beurt naar de volgende speler. Hieronder de log

        player 2        left: 6, 1, 1, 1, 1, 1,         right: 1, 1, 1, 1, 1, 2,
        12/12, 0/6, 0/6, 0
        Reinforcements:
        BlacksmithsHammer (1)
2: : 3,
2: : 1, 1,
3: : 4,
3: : 1,
4: :
5: : 3/2, 3/2,
6: : 2, 2,
8: : 2,
8: : 3, 3,
12: : 1+1+1+1, 2+2,

What do you want to do now? (F) Forge / (H) Heroic feat / (P) Passf
f
2: : 3,
2: : 1, 1,
3: : 4,
3: : 1,
4: :
5: : 3/2, 3/2,
6: : 2, 2,
8: : 2,
8: : 3, 3,
12: : 1+1+1+1, 2+2,

out of which pool are you going to buy (1,2,3,4,6,7,8,9,10)?8
8
which dieface do you want? (1..1)1
1
congrats you bought 2
left: 6, 1, 1, 1, 1, 1,
            right: 1, 1, 1, 1, 1, 2,
            on which die you want to forge 2?
            Left (L) or Right (R)l
l
you bought 2
                your die currently looks like this: 6,1,1,1,1,1
                which dieface you want to replace it with? (1..6)2
2
new die: 6,2,1,1,1,1

                You have 4
                Do you want to keep forging? (Y/N)y
y
2: : 3,
2: : 1, 1,
3: : 4,
3: : 1,
4: :
5: : 3/2, 3/2,
6: : 2, 2,
8: :
8: : 3, 3,
12: : 1+1+1+1, 2+2,

out of which pool are you going to buy (1,2,3,4)?2
2
which dieface do you want? (1..2)2
2
congrats you bought 1
left: 6, 2, 1, 1, 1, 1,
            right: 1, 1, 1, 1, 1, 2,
            on which die you want to forge 1?
            Left (L) or Right (R)r
r
you bought 1
                your die currently looks like this: 1,1,1,1,1,2
                which dieface you want to replace it with? (1..6)1
1
new die: 1,1,1,1,1,2

            you have 6 gold to distribute
            your hammer already contains 0
            your current treasure contains 2/12
            how much would you like to add to the hammer? (0..6)
            Everything else will go to your regular gold resource0                                                                                           
0

**Comment by thomashertog** [comment]
fixed!
kudos wel voor de uitgebreide bug report! 👍
